# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOdAekPlj7my43i5FyTbPwWHXFo-gfhB
"""

"""Function to return the factorial of a number using recursion"""
def find_factorial(n):
  if n == 1:
      return n
  else:
      return n*find_factorial(n-1)

"""Function to return a True if number is a curious number"""
def is_curious(num):
   number = list(str(num))
   sum = 0
   if len(str(num)) > 1:
     for digit in number:
       sum += find_factorial(int(digit))
       if sum == num:
         return True
     else:
       return False
   else:
     return False

is_curious(1)

is_curious(145)